language: php
sudo: false

php:
  - 5.6
  - 5.5
env:

matrix:
  fast_finish: true

before_script:
  - composer install

script:
  - phpunit -c build/phpunit.xml

build:
    tests:
        override:
            -
                command: 'phpunit -c build/phpunit.xml --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'